version: '3'

services:
  resource-service:
    build: './resource-service'
    image: 'resource-service:1.0.0'
    container_name: 'resource-service-v1'
    depends_on:
      - 'resource-db'
    ports:
      - '8081:8080'
    env_file:
      - 'config/resource.env'

  song-service:
    build: './song-service'
    image: 'song-service:1.0.0'
    container_name: 'song-service-v1'
    depends_on:
      - 'song-db'
    ports:
      - '8082:8080'
    env_file:
      - 'config/song.env'

  resource-db:
    image: 'postgres:16.1'
    container_name: "resource-db"
    ports:
      - '5433:5432'
    env_file:
      - 'config/resource.env'
    volumes:
      - './config/resource.sql:/docker-entrypoint-initdb.d/resource.sql'

  song-db:
    image: 'postgres:16.1'
    container_name: "song-db"
    ports:
      - '5434:5432'
    env_file:
      - 'config/song.env'
    volumes:
      - './config/song.sql:/docker-entrypoint-initdb.d/song.sql'