version: '3'

services:
  eureka-service-registry:
    build: './eureka-service-registry'
    image: 'eureka-service-registry:1.0.0'
    ports:
      - '8761:8761'
    env_file:
      - 'config/eureka.env'

  resource-service:
    build: './resource-service'
    image: 'resource-service:1.0.0'
    depends_on:
      - 'resource-db'
      - 'eureka-service-registry'
    ports:
      - '8081:8080'
    links:
      - 'eureka-service-registry'
    env_file:
      - 'config/resource.env'

  song-service:
    build: './song-service'
    image: 'song-service:1.0.0'
    deploy:
      mode: 'replicated'
      replicas: 2
    depends_on:
      - 'song-db'
      - 'eureka-service-registry'
    ports:
      - '8082-8083:8080'
    env_file:
      - 'config/song.env'

  resource-db:
    image: 'postgres:16.1'
    ports:
      - '5433:5432'
    env_file:
      - 'config/resource.env'
    volumes:
      - './config/resource.sql:/docker-entrypoint-initdb.d/resource.sql'

  song-db:
    image: 'postgres:16.1'
    ports:
      - '5434:5432'
    env_file:
      - 'config/song.env'
    volumes:
      - './config/song.sql:/docker-entrypoint-initdb.d/song.sql'