version: '3'

services:
  postgres:
    image: 'postgres:16.1'
    container_name: 'resource-postgres'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=resource-db'
    volumes:
      - './src/main/resources/audiofile.sql:/docker-entrypoint-initdb.d/audiofile.sql'