version: '3'

services:
  postgres:
    image: 'postgres:16.1'
    container_name: 'postgresql'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=resources'