version: '3'

services:
  postgres:
    image: 'postgres:16.1'
    container_name: 'song-postgres'
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=song-db'
    volumes:
      - './src/main/resources/song.sql:/docker-entrypoint-initdb.d/song.sql'